### ISSUE TITLE
Propose and implement new test cases for the Pysat-based plugin

### ISSUE THREAD

**Issue by jagalindo** [flamapy/pysat_metamodel#49]
Currently there are some tests that use cnf as inputs and which we know what is the expected output. However, this wont find any errors within our codebase. Therefore we need to design better tests that verify properly our questions implementation.

**Comment by jagalindo** [comment]
@pabpazjim Please provide support to @benavidescuevas in case of not understanding the current test suite.

**Comment by jagalindo** [comment]
I'm editing this to specify that test for all reaseoners would be needed. Also adding @Virako to this issue for support

**Comment by Virako** [comment]
Estimated time for help.
Estimated time: 4 hours
Estimated completion date: 02/06/2022
