### ISSUE TITLE
Operations are using "Feature" objects

### ISSUE THREAD

**Issue by jmhorcas** [flamapy/pysat_metamodel#57]
Some operations (e.g., ValidProduct, ValidConfiguration) are currently using features as objects. For example, they use the "name" attribute (.name) which may be not available in the Pysat model. This error ocurrs when loading a SAT model without translating it from the FM, as for example when loading a dimacs or a CNF directly to Pysat.

**Comment by jagalindo** [comment]
.This is now homogeneized
